### ISSUE TITLE
sudo python Pioneer600.py

### ISSUE THREAD

**Issue by geyseran** [tayfunulu/Pioneer600#1]
When I run the 'sudo python Pioneer600.py' command, I get the following errors and the OLED display stays blank:
Traceback (most recent call last):
  File "Pioneer600.py", line 276, in <module>
    bmp = BMP180()
  File "/home/pi/Pioneer600/Pioneer600/BMP180.py", line 40, in __init__
    self._load_calibration()
  File "/home/pi/Pioneer600/Pioneer600/BMP180.py", line 59, in _load_calibration
    self.cal_AC1 = self._read_s16(BMP180_CAL_AC1)   # INT16
  File "/home/pi/Pioneer600/Pioneer600/BMP180.py", line 50, in _read_s16
    result = self._read_u16(cmd)
  File "/home/pi/Pioneer600/Pioneer600/BMP180.py", line 45, in _read_u16
    MSB = self._bus.read_byte_data(self._address,cmd)
IOError: [Errno 110] Connection timed out

**Comment by tayfunulu** [comment]
hi, did you enable spi and I2C modules of raspi 

please check **"details installation"** under readme file which i added now

And you have to enable spi, i2c, 1-Wire. There are two way, in terminal or application in desktop mode.
 
İn terminal screen
sudo raspi-config
 
Under Advanced Option -> Enable SPI, I2C, 1-Wire
 
And restart….


try and let me know

TULU

**Comment by geyseran** [comment]
Hi,

 

Thanks for the information. I managed to get this working. I needed to install kodi and python-smbus.

 

Regards,

Andre

**Comment by r6dfr** [comment]
please help me

pi@raspberrypi:~/Pioneer600 $ sudo python Pioneer600.py
Traceback (most recent call last):
  File "Pioneer600.py", line 276, in <module>
    bmp = BMP180()
  File "/home/pi/Pioneer600/BMP180.py", line 40, in __init__
    self._load_calibration()
  File "/home/pi/Pioneer600/BMP180.py", line 59, in _load_calibration
    self.cal_AC1 = self._read_s16(BMP180_CAL_AC1)   # INT16
  File "/home/pi/Pioneer600/BMP180.py", line 50, in _read_s16
    result = self._read_u16(cmd)
  File "/home/pi/Pioneer600/BMP180.py", line 45, in _read_u16
    MSB = self._bus.read_byte_data(self._address,cmd)
IOError: [Errno 121] Remote I/O error
pi@raspberrypi:~/Pioneer600 $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: 20 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- 76 --                         
pi@raspberrypi:~/Pioneer600 $

**Comment by tayfunulu** [comment]
hi ,

```
sudo apt-get install build-essential libi2c-dev i2c-tools python-dev libffi-dev
sudo pip install Image

```
And you have to enable spi, i2c, 1-Wire. 

In terminal screen

`sudo raspi-config`

Under Advanced Option -> Enable SPI, I2C, 1-Wire

And restart….

**Comment by r6dfr** [comment]
hiI did all this and adjusted it.I got a boarder pioneer 600 with a BMP280 sensor. And you have a BMP 180.At me While there is no experience to rewrite the code.24.01.2018, 20:16, "Tayfun ULU" <notifications@github.com>:hi ,
sudo apt-get install build-essential libi2c-dev i2c-tools python-dev libffi-dev
sudo pip install Image


And you have to enable spi, i2c, 1-Wire.
In terminal screen
sudo raspi-config
Under Advanced Option -> Enable SPI, I2C, 1-Wire
And restart….
